file_adoption.settings:
  type: config_object
  label: 'File Adoption settings'
  mapping:
    ignore_patterns:
      type: string
      label: 'Ignore Patterns'
    enable_adoption:
      type: boolean
      label: 'Enable Adoption'
    items_per_run:
      type: integer
      label: 'Items processed per cron run'
    folder_depth:
      type: integer
      label: 'Folder depth'
      description: 'Maximum directory depth to scan. 0 for unlimited.'
