file_adoption.settings:
  type: config_object
  label: 'File Adoption settings'
  mapping:
    ignore_patterns:
      type: string
      label: 'Ignore Patterns'
    enable_adoption:
      type: boolean
      label: 'Enable Adoption'
    add_to_media:
      type: boolean
      label: 'Add to Media'
      description: 'Add to Media'
      default_value: false
