file_adoption.settings:
  type: config_object
  label: 'File Adoption settings'
  mapping:
    ignore_patterns:
      type: string
      label: 'Ignore Patterns'
    enable_adoption:
      type: boolean
      label: 'Enable Adoption'
    items_per_run:
      type: integer
      label: 'Items processed per cron run'
    follow_symlinks:
      type: boolean
      label: 'Follow symbolic links'
    cache_lifetime:
      type: integer
      label: 'Inventory cache lifetime'
