file_adoption.settings:
  type: config_object
  label: 'File Adoption settings'
  mapping:
    ignore_patterns:
      type: string
      label: 'Ignore Patterns'
    enable_adoption:
      type: boolean
      label: 'Enable Adoption'
    items_per_run:
      type: integer
      label: 'Items processed per cron run'
    ignore_symlinks:
      type: boolean
      label: 'Ignore Symlinks'
    directory_depth:
      type: integer
      label: 'Directory depth'
      range:
        min: 1
        max: 9
    cron_frequency:
      type: string
      label: 'Cron frequency'
    verbose_logging:
      type: boolean
      label: 'Verbose Logging'
