file_adoption.settings:
  type: config_object
  label: 'File Adoption settings'
  mapping:
    ignore_patterns:
      type: string
      label: 'Ignore Patterns'
    enable_adoption:
      type: boolean
      label: 'Enable Adoption'
    items_per_run:
      type: integer
      label: 'Items processed per cron run'
    follow_symlinks:
      type: boolean
      label: 'Follow symbolic links'
    scan_depth:
      type: integer
      label: 'Maximum scan depth'
    debug_log_path:
      type: string
      label: 'Debug log path'
      description: 'File path to record detailed scan logs'
